
##项目名称
spring:
        application:
                    name: service-client
#项目端口号
server:
        port: 8173


 ##eureka服务注册发现中心
eureka:
       client:
              serviceUrl:
                         defaultZone: http://localhost:8172/eureka/