spring:
         application:
                      name: service-consumer-feign-hystrix
server:
       port: 8176

eureka:
        client:
                serviceUrl:
                            defaultZone: http://localhost:8172/eureka/