spring:
        application:
                      name: service-consumer-feign
server:
       port: 8175


eureka:
        client:
                serviceUrl:
                            defaultZone: http://localhost:8172/eureka/
feign:
      hystrix:
               enabled: true
