spring:
       application:
                    name: service-zuul
server:
        port: 8177

eureka:
       client:
              serviceUrl:
                          defaultZone: http://localhost:8172/eureka/
zuul:
       routes:
               index.path: /index/**
               index.url: forward:/home
               api-a:
                     path: /api-a/**
                     serviceId: service-consumer
               api-b:
                     path: /api-b/**
                     serviceId: service-consumer-feign

               baidu:
                      path: /baidu/**
                      url: http://www.baidu.com


               api:
                   path: /api/**
                   stripPrefix: false

api:
    ribbon:
    listOfServers : 192.168.1.100:8080,192.168.1.101:8080,192.168.1.102:8080


